# Integração Parte 1 - Python para "Criar" Bases de Dados

### Qual arquivo vamos importar?

- Vamos usar o mesmo exemplo que usamos da empresa Contoso no módulo de Análise de Dados

Temos 4 arquivos diferentes:
- Vendas
- Lojas
- Clientes
- Produtos

E vamos integrar eles em 1 arquivo único apenas com as informações relevantes. Depois, vamos importar essa base tratada para o Power BI

In [1]:
import pandas as pd
import os
#importando os arquivos
caminho_padrao = r'C:\Users\leand\OneDrive\Documentos\Hashtag Treinamentos Python\Python com o Power BI'
vendas_df = pd.read_csv(os.path.join(caminho_padrao, r'Contoso Vendas 2017.csv'), sep=';')
produtos_df = pd.read_csv(os.path.join(caminho_padrao, r'Contoso - Cadastro Produtos.csv'), sep=';')
lojas_df = pd.read_csv(os.path.join(caminho_padrao, r'Contoso - Lojas.csv'), sep=';')
clientes_df = pd.read_csv(os.path.join(caminho_padrao, r'Contoso - Clientes.csv'), sep=';')

#limpando apenas as colunas que queremos
clientes_df = clientes_df[['ID Cliente', 'E-mail']]
produtos_df = produtos_df[['ID Produto', 'Nome do Produto']]
lojas_df = lojas_df[['ID Loja', 'Nome da Loja']]

#mesclando e renomeando os dataframes
vendas_df = vendas_df.merge(produtos_df, on='ID Produto')
vendas_df = vendas_df.merge(lojas_df, on='ID Loja')
vendas_df = vendas_df.merge(clientes_df, on='ID Cliente').rename(columns={'E-mail': 'E-mail do Cliente'})
#display(vendas_df)

,Numero da Venda,Data da Venda,Data do Envio,ID Canal,ID Loja,ID Produto,ID Promocao,ID Cliente,Quantidade Vendida,Quantidade Devolvida,Nome do Produto,Nome da Loja,E-mail do Cliente
0,1,01/01/2017,02/01/2017,1,86,981,2,6825,9,1,A. Datum Advanced Digital Camera M300 Pink,Loja Contoso Austin,rbrumfieldmy@ameblo.jp
1,880458,23/11/2017,23/11/2017,0,306,235,10,6825,8,0,Litware Home Theater System 7.1 Channel M710 B...,Loja Contoso Europe Online,rbrumfieldmy@ameblo.jp
2,191019,20/03/2017,21/03/2017,1,172,376,2,6825,9,0,Adventure Works Laptop12 M1201 Silver,Loja Contoso Hartford,rbrumfieldmy@ameblo.jp
3,18610,08/01/2017,10/01/2017,2,200,448,2,6825,48,0,WWI Desktop PC1.80 E1801 Black,Loja Contoso Catalog,rbrumfieldmy@ameblo.jp
4,287704,23/04/2017,26/04/2017,3,76,280,1,6825,10,0,Contoso Home Theater System 2.1 Channel M1210 ...,Loja Contoso Beaumont No.1,rbrumfieldmy@ameblo.jp
...,...,...,...,...,...,...,...,...,...,...,...,...,...
980637,878244,23/11/2017,23/11/2017,0,110,889,4,347,12,1,Contoso Bluetooth Notebook Mouse E70 Silver,Loja Contoso Orlando,edowner9m@imdb.com
980638,920243,09/12/2017,10/12/2017,1,261,1367,5,38781,13,0,Contoso Expandable 3-Handset Cordless Phone Sy...,Loja Contoso Damascus No.1,ruben31@adventure-works.com
980639,467482,21/06/2017,25/06/2017,4,115,269,1,553,10,0,Contoso Home Theater System 4.1 Channel M1400 ...,Loja Contoso New York No.1,akuhnertfc@themeforest.net
980640,853643,13/11/2017,20/11/2017,7,115,809,4,38860,6,0,Contoso Dual USB Power Adapter - power adapter...,Loja Contoso New York No.1,anne5@adventure-works.com
980641,903958,02/12/2017,02/12/2017,0,222,1435,10,815,8,0,The Phone Company Touch Screen Phones SAW/On-w...,Loja Contoso Roma,ekorneevmm@instagram.com

In [3]:
#limpando apenas as colunas que queremos
clientes_df = clientes_df[['ID Cliente', 'E-mail']]
produtos_df = produtos_df[['ID Produto', 'Nome do Produto']]
lojas_df = lojas_df[['ID Loja', 'Nome da Loja']]
display(clientes_df)
display(produtos_df)
display(lojas_df)

       ID Cliente                         E-mail
0               1    glanfranchi0@mayoclinic.com
1               2      lroseblade1@bigcartel.com
2               3      gishchenko2@moonfruit.com
3               4    bjedrzejewsky3@e-recht24.de
4               5       sbredbury4@sitemeter.com
...           ...                            ...
39499       39500    brandy0@adventure-works.com
39500       39501   alicia12@adventure-works.com
39501       39502    connie4@adventure-works.com
39502       39503    shawn23@adventure-works.com
39503       39504  lindsey10@adventure-works.com

[39504 rows x 2 columns]

      ID Produto                                  Nome do Produto
0            873            Contoso Wireless Laser Mouse E50 Grey
1            879    Contoso Optical Wheel OEM PS/2 Mouse E60 Grey
2            880   Contoso Optical Wheel OEM PS/2 Mouse E60 Black
3            881   Contoso Optical Wheel OEM PS/2 Mouse E60 White
4            882  Contoso Optical Wheel OEM PS/2 Mouse E60 Silver
...          ...                                              ...
1685        1602        SV DVD 12-Inch Player Portable M400 Black
1686        1606        SV DVD 9-Inch Player Portable M300 Silver
1687        1607       SV DVD 12-Inch Player Portable M400 Silver
1688        1611         SV DVD 9-Inch Player Portable M300 White
1689        1612        SV DVD 12-Inch Player Portable M400 White

[1690 rows x 2 columns]

     ID Loja                         Nome da Loja
0          1           Loja Contoso Seattle No.1
1          2           Loja Contoso Seattle No.2
2          3              Loja Contoso Kennewick
3          4               Loja Contoso Bellevue
4          5                Loja Contoso Redmond
..       ...                                  ...
301      306          Loja Contoso Europe Online
302      307            Loja Contoso Asia Online
303      308  Loja Contoso North America Reseller
304      309         Loja Contoso Europe Reseller
305      310           Loja Contoso Asia Reseller

[306 rows x 2 columns]

In [4]:
#mesclando e renomeando os dataframes
vendas_df = vendas_df.merge(produtos_df, on='ID Produto')
vendas_df = vendas_df.merge(lojas_df, on='ID Loja')
vendas_df = vendas_df.merge(clientes_df, on='ID Cliente').rename(columns={'E-mail': 'E-mail do Cliente'})
display(vendas_df)

,Numero da Venda,Data da Venda,Data do Envio,ID Canal,ID Loja,ID Produto,ID Promocao,ID Cliente,Quantidade Vendida,Quantidade Devolvida,Nome do Produto_x,Nome da Loja_x,E-mail do Cliente,Nome do Produto_y,Nome da Loja_y,E-mail do Cliente
0,1,01/01/2017,02/01/2017,1,86,981,2,6825,9,1,A. Datum Advanced Digital Camera M300 Pink,Loja Contoso Austin,rbrumfieldmy@ameblo.jp,A. Datum Advanced Digital Camera M300 Pink,Loja Contoso Austin,rbrumfieldmy@ameblo.jp
1,880458,23/11/2017,23/11/2017,0,306,235,10,6825,8,0,Litware Home Theater System 7.1 Channel M710 B...,Loja Contoso Europe Online,rbrumfieldmy@ameblo.jp,Litware Home Theater System 7.1 Channel M710 B...,Loja Contoso Europe Online,rbrumfieldmy@ameblo.jp
2,18610,08/01/2017,10/01/2017,2,200,448,2,6825,48,0,WWI Desktop PC1.80 E1801 Black,Loja Contoso Catalog,rbrumfieldmy@ameblo.jp,WWI Desktop PC1.80 E1801 Black,Loja Contoso Catalog,rbrumfieldmy@ameblo.jp
3,180875,16/03/2017,16/03/2017,0,268,975,6,6825,4,0,A. Datum Ultra Compact Digital Camera M190 Pink,Loja Contoso Tokyo No.2,rbrumfieldmy@ameblo.jp,A. Datum Ultra Compact Digital Camera M190 Pink,Loja Contoso Tokyo No.2,rbrumfieldmy@ameblo.jp
4,191019,20/03/2017,21/03/2017,1,172,376,2,6825,9,0,Adventure Works Laptop12 M1201 Silver,Loja Contoso Hartford,rbrumfieldmy@ameblo.jp,Adventure Works Laptop12 M1201 Silver,Loja Contoso Hartford,rbrumfieldmy@ameblo.jp
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
980637,150948,03/03/2017,03/03/2017,0,81,486,2,38931,4,0,Proseware CRT19 E201 White,Loja Contoso Bacliff,jackson48@adventure-works.com,Proseware CRT19 E201 White,Loja Contoso Bacliff,jackson48@adventure-works.com
980638,414804,04/06/2017,07/06/2017,3,81,895,1,39074,5,0,SV Keyboard E90 Silver,Loja Contoso Bacliff,jesse32@adventure-works.com,SV Keyboard E90 Silver,Loja Contoso Bacliff,jesse32@adventure-works.com
980639,860842,16/11/2017,17/11/2017,1,158,759,4,38701,6,1,Contoso 90W AC/DC Power Adapter E300 Black,Loja Contoso Haverhill,ana20@adventure-works.com,Contoso 90W AC/DC Power Adapter E300 Black,Loja Contoso Haverhill,ana20@adventure-works.com
980640,903958,02/12/2017,02/12/2017,0,222,1435,10,815,8,0,The Phone Company Touch Screen Phones SAW/On-w...,Loja Contoso Roma,ekorneevmm@instagram.com,The Phone Company Touch Screen Phones SAW/On-w...,Loja Contoso Roma,ekorneevmm@instagram.com
980641,183653,17/03/2017,19/03/2017,2,85,1071,2,39118,9,0,"A. Datum SLR Camera 35"" M358 Blue",Loja Contoso Spring,mary9@adventure-works.com,"A. Datum SLR Camera 35"" M358 Blue",Loja Contoso Spring,mary9@adventure-works.com