### Alpha Vantage

https://www.alphavantage.co/documentation/

#### Pegando cotações semanais - JSON

In [1]:
from chave import chave_api

import requests

# replace the "demo" apikey below with your own key from https://www.alphavantage.co/support/#api-key
url = f'https://www.alphavantage.co/query?function=TIME_SERIES_MONTHLY&symbol=GOOG&apikey={chave_api}'
r = requests.get(url)
data = r.json()

print(data)

{'Meta Data': {'1. Information': 'Monthly Prices (open, high, low, close) and Volumes', '2. Symbol': 'GOOG', '3. Last Refreshed': '2022-10-31', '4. Time Zone': 'US/Eastern'}, 'Monthly Time Series': {'2022-10-31': {'1. open': '97.2200', '2. high': '105.0999', '3. low': '91.9000', '4. close': '94.6600', '5. volume': '584616310'}, '2022-09-30': {'1. open': '109.2000', '2. high': '112.6400', '3. low': '96.0300', '4. close': '96.1500', '5. volume': '532842467'}, '2022-08-31': {'1. open': '115.5300', '2. high': '123.2600', '3. low': '108.8000', '4. close': '109.1500', '5. volume': '430922710'}, '2022-07-29': {'1. open': '2166.7400', '2. high': '2408.7000', '3. low': '104.7600', '4. close': '116.6400', '5. volume': '339525726'}, '2022-06-30': {'1. open': '2298.6300', '2. high': '2387.9696', '3. low': '2112.5706', '4. close': '2187.4500', '5. volume': '31358279'}, '2022-05-31': {'1. open': '2278.1300', '2. high': '2462.8600', '3. low': '2044.1600', '4. close': '2280.7800', '5. volume': '35869499'}, '2022-04-29': {'1. open': '2800.2000', '2. high': '2880.8750', '3. low': '2262.4850', '4. close': '2299.3300', '5. volume': '28022017'}, '2022-03-31': {'1. open': '2689.6000', '2. high': '2883.2500', '3. low': '2517.2150', '4. close': '2792.9900', '5. volume': '31811236'}, '2022-02-28': {'1. open': '2756.7000', '2. high': '3042.0000', '3. low': '2495.2900', '4. close': '2697.8200', '5. volume': '36609705'}, '2022-01-31': {'1. open': '2889.5100', '2. high': '2932.2000', '3. low': '2492.8390', '4. close': '2713.9700', '5. volume': '30699124'}, '2021-12-31': {'1. open': '2884.2500', '2. high': '2992.1000', '3. low': '2805.0000', '4. close': '2893.5900', '5. volume': '23950206'}, '2021-11-30': {'1. open': '2963.3000', '2. high': '3037.0000', '3. low': '2841.3200', '4. close': '2849.0400', '5. volume': '22120136'}, '2021-10-29': {'1. open': '2671.0900', '2. high': '2982.3600', '3. low': '2623.3300', '4. close': '2965.4100', '5. volume': '24830507'}, '2021-09-30': {'1. open': '2913.0000', '2. high': '2936.4099', '3. low': '2660.0000', '4. close': '2665.3100', '5. volume': '25265626'}, '2021-08-31': {'1. open': '2709.6900', '2. high': '2929.7899', '3. low': '2683.6700', '4. close': '2909.2400', '5. volume': '18615809'}, '2021-07-30': {'1. open': '2496.9950', '2. high': '2800.2200', '3. low': '2496.9950', '4. close': '2704.4200', '5. volume': '22824857'}, '2021-06-30': {'1. open': '2422.0000', '2. high': '2555.9200', '3. low': '2382.8300', '4. close': '2506.3200', '5. volume': '27425377'}, '2021-05-28': {'1. open': '2402.7200', '2. high': '2442.9440', '3. low': '2230.0500', '4. close': '2411.5600', '5. volume': '25456404'}, '2021-04-30': {'1. open': '2097.9500', '2. high': '2452.3780', '3. low': '2096.8900', '4. close': '2410.1200', '5. volume': '30727072'}, '2021-03-31': {'1. open': '2056.5200', '2. high': '2128.8100', '3. low': '2010.0000', '4. close': '2068.6300', '5. volume': '34796574'}, '2021-02-26': {'1. open': '1853.5700', '2. high': '2152.6800', '3. low': '1850.9300', '4. close': '2036.8600', '5. volume': '29111908'}, '2021-01-29': {'1. open': '1757.5400', '2. high': '1934.8600', '3. low': '1699.0000', '4. close': '1835.7400', '5. volume': '33082794'}, '2020-12-31': {'1. open': '1774.3700', '2. high': '1847.2000', '3. low': '1699.0000', '4. close': '1751.8800', '5. volume': '31422606'}, '2020-11-30': {'1. open': '1628.1600', '2. high': '1818.0600', '3. low': '1616.0300', '4. close': '1760.7400', '5. volume': '34952246'}, '2020-10-30': {'1. open': '1484.2700', '2. high': '1687.0000', '3. low': '1436.0000', '4. close': '1621.0100', '5. volume': '39260343'}, '2020-09-30': {'1. open': '1636.6300', '2. high': '1733.1799', '3. low': '1406.5500', '4. close': '1469.6000', '5. volume': '40570621'}, '2020-08-31': {'1. open': '1486.6400', '2. high': '1659.2200', '3. low': '1458.6500', '4. close': '1634.1800', '5. volume': '37293396'}, '2020-07-31': {'1. open': '1411.1000', '2. high': '1586.9900', '3. low': '1409.8200', '4. close': '1482.9600', '5. volume': '35346094'}, '2020-06-30': {'1. open': '1418.3900', '2. high': '1475.9410', '3. low': '1347.0100', '4. close': '1413.6100', '5. volume': '38833324'}, '2020-05-29': {'1. open': '1328.5000', '2. high': '1441.0000', '3. low': '1299.0000', '4. close': '1428.9200', '5. volume': '31883800'}, '2020-04-30': {'1. open': '1122.0000', '2. high': '1359.9900', '3. low': '1079.8100', '4. close': '1348.6600', '5. volume': '46336723'}, '2020-03-31': {'1. open': '1351.6100', '2. high': '1410.1500', '3. low': '1013.5360', '4. close': '1162.8100', '5. volume': '71398419'}, '2020-02-28': {'1. open': '1462.0000', '2. high': '1532.1060', '3. low': '1271.0000', '4. close': '1339.3300', '5. volume': '37103140'}, '2020-01-31': {'1. open': '1341.5500', '2. high': '1503.2140', '3. low': '1341.5500', '4. close': '1434.2300', '5. volume': '33406912'}, '2019-12-31': {'1. open': '1301.0000', '2. high': '1365.0000', '3. low': '1279.0000', '4. close': '1337.0200', '5. volume': '27627707'}, '2019-11-29': {'1. open': '1265.0000', '2. high': '1335.5290', '3. low': '1260.5000', '4. close': '1304.9600', '5. volume': '24956906'}, '2019-10-31': {'1. open': '1219.0000', '2. high': '1299.3100', '3. low': '1162.4300', '4. close': '1260.1100', '5. volume': '29219555'}, '2019-09-30': {'1. open': '1177.0300', '2. high': '1248.3000', '3. low': '1163.2000', '4. close': '1219.0000', '5. volume': '27186490'}, '2019-08-30': {'1. open': '1214.0300', '2. high': '1234.1100', '3. low': '1140.1400', '4. close': '1188.1000', '5. volume': '28921401'}, '2019-07-31': {'1. open': '1098.0000', '2. high': '1265.5500', '3. low': '1093.7030', '4. close': '1216.6800', '5. volume': '32952483'}, '2019-06-28': {'1. open': '1065.5000', '2. high': '1124.1100', '3. low': '1025.0000', '4. close': '1080.9100', '5. volume': '34098832'}, '2019-05-31': {'1. open': '1188.0500', '2. high': '1190.8500', '3. low': '1100.1800', '4. close': '1103.6300', '5. volume': '33323762'}, '2019-04-30': {'1. open': '1184.1000', '2. high': '1289.2700', '3. low': '1175.0000', '4. close': '1188.4800', '5. volume': '27860634'}, '2019-03-29': {'1. open': '1124.9000', '2. high': '1231.7900', '3. low': '1123.3000', '4. close': '1173.3100', '5. volume': '31658936'}, '2019-02-28': {'1. open': '1112.4000', '2. high': '1147.0000', '3. low': '1086.0000', '4. close': '1119.9200', '5. volume': '28934646'}, '2019-01-31': {'1. open': '1016.5700', '2. high': '1117.3300', '3. low': '1014.0700', '4. close': '1116.3700', '5. volume': '30714651'}, '2018-12-31': {'1. open': '1123.1400', '2. high': '1124.6500', '3. low': '970.1100', '4. close': '1035.6100', '5. volume': '40256461'}, '2018-11-30': {'1. open': '1075.8000', '2. high': '1095.5700', '3. low': '996.0200', '4. close': '1094.4300', '5. volume': '36735570'}, '2018-10-31': {'1. open': '1199.8900', '2. high': '1209.9600', '3. low': '995.8300', '4. close': '1076.7700', '5. volume': '48496167'}, '2018-09-28': {'1. open': '1204.2700', '2. high': '1212.9900', '3. low': '1146.9100', '4. close': '1193.4700', '5. volume': '28863199'}, '2018-08-31': {'1. open': '1228.0000', '2. high': '1256.5000', '3. low': '1188.2400', '4. close': '1218.1900', '5. volume': '28820379'}, '2018-07-31': {'1. open': '1099.0000', '2. high': '1273.8900', '3. low': '1093.8000', '4. close': '1217.2600', '5. volume': '31953386'}, '2018-06-29': {'1. open': '1099.3500', '2. high': '1186.2860', '3. low': '1096.0100', '4. close': '1115.6500', '5. volume': '32103642'}, '2018-05-31': {'1. open': '1013.6600', '2. high': '1110.7500', '3. low': '1006.2900', '4. close': '1084.9900', '5. volume': '31849196'}, '2018-04-30': {'1. open': '1022.8200', '2. high': '1094.1650', '3. low': '990.3700', '4. close': '1017.3300', '5. volume': '41773275'}, '2018-03-29': {'1. open': '1107.8700', '2. high': '1177.0500', '3. low': '980.6400', '4. close': '1031.7900', '5. volume': '43301942'}, '2018-02-28': {'1. open': '1162.6100', '2. high': '1174.0000', '3. low': '992.5600', '4. close': '1104.7300', '5. volume': '40388224'}, '2018-01-31': {'1. open': '1048.3400', '2. high': '1186.8900', '3. low': '1045.2300', '4. close': '1169.9400', '5. volume': '27111134'}, '2017-12-29': {'1. open': '1015.8000', '2. high': '1078.4900', '3. low': '988.2800', '4. close': '1046.4000', '5. volume': '27458240'}, '2017-11-30': {'1. open': '1017.2100', '2. high': '1062.3800', '3. low': '1013.0100', '4. close': '1021.4100', '5. volume': '23723565'}, '2017-10-31': {'1. open': '959.9800', '2. high': '1048.3900', '3. low': '947.8400', '4. close': '1016.6400', '5. volume': '30768015'}, '2017-09-29': {'1. open': '941.1300', '2. high': '959.7864', '3. low': '909.7000', '4. close': '959.1100', '5. volume': '27177858'}, '2017-08-31': {'1. open': '932.3800', '2. high': '941.9800', '3. low': '903.4000', '4. close': '939.3300', '5. volume': '27325965'}, '2017-07-31': {'1. open': '912.1800', '2. high': '986.2000', '3. low': '894.7900', '4. close': '930.5000', '5. volume': '35416014'}, '2017-06-30': {'1. open': '968.9500', '2. high': '988.2500', '3. low': '908.3100', '4. close': '908.7300', '5. volume': '42736021'}, '2017-05-31': {'1. open': '901.9400', '2. high': '979.2700', '3. low': '901.4500', '4. close': '964.8600', '5. volume': '31802202'}, '2017-04-28': {'1. open': '829.2200', '2. high': '916.8500', '3. low': '817.0201', '4. close': '905.9600', '5. volume': '24742467'}, '2017-03-31': {'1. open': '828.8500', '2. high': '853.5000', '3. low': '803.3700', '4. close': '829.5600', '5. volume': '33840342'}, '2017-02-28': {'1. open': '799.6800', '2. high': '833.4500', '3. low': '791.1900', '4. close': '823.2100', '5. volume': '25689522'}, '2017-01-31': {'1. open': '778.8100', '2. high': '841.9500', '3. low': '775.8000', '4. close': '796.7900', '5. volume': '33332821'}, '2016-12-30': {'1. open': '757.4400', '2. high': '804.3799', '3. low': '737.0245', '4. close': '771.8200', '5. volume': '32097980'}, '2016-11-30': {'1. open': '782.8900', '2. high': '795.6330', '3. low': '727.5400', '4. close': '758.0400', '5. volume': '42688236'}, '2016-10-31': {'1. open': '774.2500', '2. high': '816.6800', '3. low': '769.5000', '4. close': '784.5400', '5. volume': '33956196'}, '2016-09-30': {'1. open': '769.2500', '2. high': '789.8500', '3. low': '754.0001', '4. close': '777.2900', '5. volume': '27600794'}, '2016-08-31': {'1. open': '761.0900', '2. high': '789.7500', '3. low': '761.0900', '4. close': '767.0500', '5. volume': '26385341'}, '2016-07-29': {'1. open': '692.2000', '2. high': '778.5500', '3. low': '688.2150', '4. close': '768.7900', '5. volume': '29914808'}, '2016-06-30': {'1. open': '734.5300', '2. high': '737.2100', '3. low': '663.2840', '4. close': '692.1000', '5. volume': '39375913'}, '2016-05-31': {'1. open': '697.6300', '2. high': '739.7300', '3. low': '689.0100', '4. close': '735.7200', '5. volume': '35000414'}, '2016-04-29': {'1. open': '738.6000', '2. high': '769.9000', '3. low': '689.0000', '4. close': '693.0100', '5. volume': '42154738'}, '2016-03-31': {'1. open': '703.6200', '2. high': '757.8800', '3. low': '685.3400', '4. close': '744.9500', '5. volume': '41727507'}, '2016-02-29': {'1. open': '750.4600', '2. high': '789.8699', '3. low': '663.0600', '4. close': '697.7700', '5. volume': '64367114'}, '2016-01-29': {'1. open': '743.0000', '2. high': '752.0000', '3. low': '673.2600', '4. close': '742.9500', '5. volume': '46561234'}, '2015-12-31': {'1. open': '747.1100', '2. high': '779.9800', '3. low': '724.1700', '4. close': '758.8800', '5. volume': '43110708'}, '2015-11-30': {'1. open': '711.0600', '2. high': '762.7075', '3. low': '705.8500', '4. close': '742.6000', '5. volume': '33934938'}, '2015-10-30': {'1. open': '608.3700', '2. high': '730.0000', '3. low': '599.8500', '4. close': '710.8100', '5. volume': '49513250'}, '2015-09-30': {'1. open': '602.3600', '2. high': '650.9000', '3. low': '589.3800', '4. close': '608.4200', '5. volume': '47857854'}, '2015-08-31': {'1. open': '625.3400', '2. high': '674.9000', '3. low': '565.0500', '4. close': '618.2500', '5. volume': '53395840'}, '2015-07-31': {'1. open': '524.7300', '2. high': '678.6400', '3. low': '515.1800', '4. close': '625.6100', '5. volume': '63319457'}, '2015-06-30': {'1. open': '536.7900', '2. high': '543.7400', '3. low': '520.5000', '4. close': '520.5100', '5. volume': '34342523'}, '2015-05-29': {'1. open': '538.4300', '2. high': '544.1900', '3. low': '521.0850', '4. close': '532.1100', '5. volume': '31866779'}, '2015-04-30': {'1. open': '548.6000', '2. high': '571.1400', '3. low': '521.0100', '4. close': '537.3400', '5. volume': '42283442'}, '2015-03-31': {'1. open': '560.5300', '2. high': '577.9100', '3. low': '544.2200', '4. close': '548.0000', '5. volume': '38542782'}, '2015-02-27': {'1. open': '531.7300', '2. high': '564.7100', '3. low': '518.5500', '4. close': '558.4000', '5. volume': '32508126'}, '2015-01-30': {'1. open': '529.0100', '2. high': '542.1700', '3. low': '487.5600', '4. close': '534.5200', '5. volume': '50087655'}, '2014-12-31': {'1. open': '538.9000', '2. high': '541.4100', '3. low': '489.0000', '4. close': '526.4000', '5. volume': '45796626'}, '2014-11-28': {'1. open': '555.5000', '2. high': '557.9000', '3. low': '530.0800', '4. close': '541.8300', '5. volume': '28445740'}, '2014-10-31': {'1. open': '576.0100', '2. high': '581.0000', '3. low': '508.1000', '4. close': '559.0800', '5. volume': '52083039'}, '2014-09-30': {'1. open': '571.8500', '2. high': '596.4800', '3. low': '568.2100', '4. close': '577.3600', '5. volume': '33421676'}, '2014-08-29': {'1. open': '570.4000', '2. high': '587.3400', '3. low': '560.0000', '4. close': '571.6000', '5. volume': '27586000'}, '2014-07-31': {'1. open': '578.3200', '2. high': '599.6500', '3. low': '565.0100', '4. close': '571.6000', '5. volume': '34516100'}, '2014-06-30': {'1. open': '560.7000', '2. high': '582.4500', '3. low': '538.7500', '4. close': '575.2800', '5. volume': '37898400'}, '2014-05-30': {'1. open': '527.1100', '2. high': '567.8400', '3. low': '503.3000', '4. close': '559.8900', '5. volume': '36527700'}, '2014-04-30': {'1. open': '558.7100', '2. high': '604.8300', '3. low': '502.8000', '4. close': '526.6600', '5. volume': '67171200'}}}

#### Pegando cotações semanais - CSV

In [9]:
import pandas as pd
# ele pega um texto e transforma um texto no arquivo
from io import StringIO
# replace the "demo" apikey below with your own key from https://www.alphavantage.co/support/#api-key
url = f'https://www.alphavantage.co/query?function=TIME_SERIES_MONTHLY&symbol=GOOG&apikey={chave_api}&datatype=csv'
r = requests.get(url)

tabela = pd.read_csv(StringIO(r.text))
display(tabela)

      timestamp     open       high        low    close     volume
0    2022-10-14    97.22   103.7300    95.2700    97.18  218230731
1    2022-09-30   109.20   112.6400    96.0300    96.15  532842467
2    2022-08-31   115.53   123.2600   108.8000   109.15  430922710
3    2022-07-29  2166.74  2408.7000   104.7600   116.64  339525726
4    2022-06-30  2298.63  2387.9696  2112.5706  2187.45   31358279
..          ...      ...        ...        ...      ...        ...
98   2014-08-29   570.40   587.3400   560.0000   571.60   27586000
99   2014-07-31   578.32   599.6500   565.0100   571.60   34516100
100  2014-06-30   560.70   582.4500   538.7500   575.28   37898400
101  2014-05-30   527.11   567.8400   503.3000   559.89   36527700
102  2014-04-30   558.71   604.8300   502.8000   526.66   67171200

[103 rows x 6 columns]

### Cotações

In [15]:
acoes = ['ITUB4', 'ABEV3', 'BBAS3']

compilada = pd.DataFrame()

for acao in acoes:
    url = f'https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol={acao}.SAO&apikey={chave_api}&datatype=csv'
    r = requests.get(url)
    tabela = pd.read_csv(StringIO(r.text))
    lista_tabelas = [compilada, tabela]
    compilada = pd.concat(lista_tabelas)
    
display(compilada)

,symbol,open,high,low,price,volume,latestDay,previousClose,change,changePercent
0,ITUB4.SAO,28.75,29.17,28.50,28.65,40087100,2022-10-14,28.64,0.01,0.0349%
0,ABEV3.SAO,15.02,15.12,14.79,14.83,16936000,2022-10-14,15.01,-0.18,-1.1992%
0,BBAS3.SAO,39.66,40.18,38.68,39.16,12435500,2022-10-14,39.38,-0.22,-0.5587%

### Encontrar ativos

In [20]:
url = f'https://www.alphavantage.co/query?function=SYMBOL_SEARCH&keywords=amazon&apikey={chave_api}&datatype=csv'
r = requests.get(url)

tabela = pd.read_csv(StringIO(r.text))
display(tabela)

,symbol,name,type,region,marketOpen,marketClose,timezone,currency,matchScore
0,AMZN,Amazon.com Inc,Equity,United States,09:30,16:00,UTC-04,USD,0.8000
1,AMZ.DEX,Amazon.com Inc,Equity,XETRA,08:00,20:00,UTC+02,EUR,0.6000
2,AMZ.FRK,Amazon.com Inc,Equity,Frankfurt,08:00,20:00,UTC+02,EUR,0.6000
3,AMZO34.SAO,Amazon.com Inc,Equity,Brazil/Sao Paolo,10:00,17:30,UTC-03,BRL,0.6000
4,0R1O.LON,Amazon.com Inc.,Equity,United Kingdom,08:00,16:30,UTC+01,USD,0.5714
5,AZFL,Amazonas Florestal Ltd,Equity,United States,09:30,16:00,UTC-04,USD,0.4286

### Informações de Resultado

In [22]:
url = f'https://www.alphavantage.co/query?function=EARNINGS&symbol=AMZN&apikey={chave_api}'
r = requests.get(url)
data = r.json()

print(data)

{'symbol': 'AMZN', 'annualEarnings': [{'fiscalDateEnding': '2022-09-30', 'reportedEPS': '-0.58'}, {'fiscalDateEnding': '2021-12-31', 'reportedEPS': '3.25'}, {'fiscalDateEnding': '2020-12-31', 'reportedEPS': '6.86'}, {'fiscalDateEnding': '2019-12-31', 'reportedEPS': '23.01'}, {'fiscalDateEnding': '2018-12-31', 'reportedEPS': '20.13'}, {'fiscalDateEnding': '2017-12-31', 'reportedEPS': '4.56'}, {'fiscalDateEnding': '2016-12-31', 'reportedEPS': '4.91'}, {'fiscalDateEnding': '2015-12-31', 'reportedEPS': '1.24'}, {'fiscalDateEnding': '2014-12-31', 'reportedEPS': '-0.54'}, {'fiscalDateEnding': '2013-12-31', 'reportedEPS': '0.58'}, {'fiscalDateEnding': '2012-12-31', 'reportedEPS': '0.42'}, {'fiscalDateEnding': '2011-12-31', 'reportedEPS': '1.37'}, {'fiscalDateEnding': '2010-12-31', 'reportedEPS': '2.53'}, {'fiscalDateEnding': '2009-12-31', 'reportedEPS': '2.03'}, {'fiscalDateEnding': '2008-12-31', 'reportedEPS': '1.5'}, {'fiscalDateEnding': '2007-12-31', 'reportedEPS': '1.12'}, {'fiscalDateEnding': '2006-12-31', 'reportedEPS': '0.45'}, {'fiscalDateEnding': '2005-12-31', 'reportedEPS': '0.84'}, {'fiscalDateEnding': '2004-12-31', 'reportedEPS': '0.93'}, {'fiscalDateEnding': '2003-12-31', 'reportedEPS': '0.6'}, {'fiscalDateEnding': '2002-12-31', 'reportedEPS': '0.0776'}, {'fiscalDateEnding': '2001-12-31', 'reportedEPS': '-0.44'}, {'fiscalDateEnding': '2000-12-31', 'reportedEPS': '-1.18'}, {'fiscalDateEnding': '1999-12-31', 'reportedEPS': '-1.17'}, {'fiscalDateEnding': '1998-12-31', 'reportedEPS': '-0.25'}, {'fiscalDateEnding': '1997-12-31', 'reportedEPS': '-0.08'}], 'quarterlyEarnings': [{'fiscalDateEnding': '2022-06-30', 'reportedDate': '2022-07-28', 'reportedEPS': '-0.2', 'estimatedEPS': '0.14', 'surprise': '-0.34', 'surprisePercentage': '-242.8571'}, {'fiscalDateEnding': '2022-03-31', 'reportedDate': '2022-04-28', 'reportedEPS': '-0.38', 'estimatedEPS': '0.42', 'surprise': '-0.8', 'surprisePercentage': '-190.4762'}, {'fiscalDateEnding': '2021-12-31', 'reportedDate': '2022-02-03', 'reportedEPS': '1.39', 'estimatedEPS': '0.18', 'surprise': '1.21', 'surprisePercentage': '672.2222'}, {'fiscalDateEnding': '2021-09-30', 'reportedDate': '2021-10-28', 'reportedEPS': '0.31', 'estimatedEPS': '0.45', 'surprise': '-0.14', 'surprisePercentage': '-31.1111'}, {'fiscalDateEnding': '2021-06-30', 'reportedDate': '2021-07-29', 'reportedEPS': '0.76', 'estimatedEPS': '0.62', 'surprise': '0.14', 'surprisePercentage': '22.5806'}, {'fiscalDateEnding': '2021-03-31', 'reportedDate': '2021-04-29', 'reportedEPS': '0.79', 'estimatedEPS': '0.48', 'surprise': '0.31', 'surprisePercentage': '64.5833'}, {'fiscalDateEnding': '2020-12-31', 'reportedDate': '2021-02-02', 'reportedEPS': '0.71', 'estimatedEPS': '0.36', 'surprise': '0.35', 'surprisePercentage': '97.2222'}, {'fiscalDateEnding': '2020-09-30', 'reportedDate': '2020-10-29', 'reportedEPS': '0.62', 'estimatedEPS': '0.37', 'surprise': '0.25', 'surprisePercentage': '67.5676'}, {'fiscalDateEnding': '2020-06-30', 'reportedDate': '2020-07-30', 'reportedEPS': '0.52', 'estimatedEPS': '0.07', 'surprise': '0.45', 'surprisePercentage': '642.8571'}, {'fiscalDateEnding': '2020-03-31', 'reportedDate': '2020-04-30', 'reportedEPS': '5.01', 'estimatedEPS': '6.25', 'surprise': '-1.24', 'surprisePercentage': '-19.84'}, {'fiscalDateEnding': '2019-12-31', 'reportedDate': '2020-01-30', 'reportedEPS': '6.47', 'estimatedEPS': '4.03', 'surprise': '2.44', 'surprisePercentage': '60.5459'}, {'fiscalDateEnding': '2019-09-30', 'reportedDate': '2019-10-24', 'reportedEPS': '4.23', 'estimatedEPS': '4.62', 'surprise': '-0.39', 'surprisePercentage': '-8.4416'}, {'fiscalDateEnding': '2019-06-30', 'reportedDate': '2019-07-25', 'reportedEPS': '5.22', 'estimatedEPS': '5.57', 'surprise': '-0.35', 'surprisePercentage': '-6.2837'}, {'fiscalDateEnding': '2019-03-31', 'reportedDate': '2019-04-25', 'reportedEPS': '7.09', 'estimatedEPS': '4.72', 'surprise': '2.37', 'surprisePercentage': '50.2119'}, {'fiscalDateEnding': '2018-12-31', 'reportedDate': '2019-01-31', 'reportedEPS': '6.04', 'estimatedEPS': '5.68', 'surprise': '0.36', 'surprisePercentage': '6.338'}, {'fiscalDateEnding': '2018-09-30', 'reportedDate': '2018-10-25', 'reportedEPS': '5.75', 'estimatedEPS': '3.14', 'surprise': '2.61', 'surprisePercentage': '83.121'}, {'fiscalDateEnding': '2018-06-30', 'reportedDate': '2018-07-26', 'reportedEPS': '5.07', 'estimatedEPS': '2.54', 'surprise': '2.53', 'surprisePercentage': '99.6063'}, {'fiscalDateEnding': '2018-03-31', 'reportedDate': '2018-04-26', 'reportedEPS': '3.27', 'estimatedEPS': '1.26', 'surprise': '2.01', 'surprisePercentage': '159.5238'}, {'fiscalDateEnding': '2017-12-31', 'reportedDate': '2018-02-01', 'reportedEPS': '2.16', 'estimatedEPS': '1.84', 'surprise': '0.32', 'surprisePercentage': '17.3913'}, {'fiscalDateEnding': '2017-09-30', 'reportedDate': '2017-10-26', 'reportedEPS': '0.52', 'estimatedEPS': '0.03', 'surprise': '0.49', 'surprisePercentage': '1633.3333'}, {'fiscalDateEnding': '2017-06-30', 'reportedDate': '2017-07-27', 'reportedEPS': '0.4', 'estimatedEPS': '1.42', 'surprise': '-1.02', 'surprisePercentage': '-71.831'}, {'fiscalDateEnding': '2017-03-31', 'reportedDate': '2017-04-27', 'reportedEPS': '1.48', 'estimatedEPS': '1.09', 'surprise': '0.39', 'surprisePercentage': '35.7798'}, {'fiscalDateEnding': '2016-12-31', 'reportedDate': '2017-02-02', 'reportedEPS': '1.54', 'estimatedEPS': '1.35', 'surprise': '0.19', 'surprisePercentage': '14.0741'}, {'fiscalDateEnding': '2016-09-30', 'reportedDate': '2016-10-27', 'reportedEPS': '0.52', 'estimatedEPS': '0.78', 'surprise': '-0.26', 'surprisePercentage': '-33.3333'}, {'fiscalDateEnding': '2016-06-30', 'reportedDate': '2016-07-28', 'reportedEPS': '1.78', 'estimatedEPS': '1.11', 'surprise': '0.67', 'surprisePercentage': '60.3604'}, {'fiscalDateEnding': '2016-03-31', 'reportedDate': '2016-04-28', 'reportedEPS': '1.07', 'estimatedEPS': '0.58', 'surprise': '0.49', 'surprisePercentage': '84.4828'}, {'fiscalDateEnding': '2015-12-31', 'reportedDate': '2016-01-28', 'reportedEPS': '1', 'estimatedEPS': '1.56', 'surprise': '-0.56', 'surprisePercentage': '-35.8974'}, {'fiscalDateEnding': '2015-09-30', 'reportedDate': '2015-10-22', 'reportedEPS': '0.17', 'estimatedEPS': '-0.14', 'surprise': '0.31', 'surprisePercentage': '221.4286'}, {'fiscalDateEnding': '2015-06-30', 'reportedDate': '2015-07-23', 'reportedEPS': '0.19', 'estimatedEPS': '-0.14', 'surprise': '0.33', 'surprisePercentage': '235.7143'}, {'fiscalDateEnding': '2015-03-31', 'reportedDate': '2015-04-23', 'reportedEPS': '-0.12', 'estimatedEPS': '-0.12', 'surprise': '0', 'surprisePercentage': '0'}, {'fiscalDateEnding': '2014-12-31', 'reportedDate': '2015-01-29', 'reportedEPS': '0.45', 'estimatedEPS': '0.17', 'surprise': '0.28', 'surprisePercentage': '164.7059'}, {'fiscalDateEnding': '2014-09-30', 'reportedDate': '2014-10-23', 'reportedEPS': '-0.95', 'estimatedEPS': '-0.73', 'surprise': '-0.22', 'surprisePercentage': '-30.137'}, {'fiscalDateEnding': '2014-06-30', 'reportedDate': '2014-07-24', 'reportedEPS': '-0.27', 'estimatedEPS': '-0.15', 'surprise': '-0.12', 'surprisePercentage': '-80'}, {'fiscalDateEnding': '2014-03-31', 'reportedDate': '2014-04-24', 'reportedEPS': '0.23', 'estimatedEPS': '0.23', 'surprise': '0', 'surprisePercentage': '0'}, {'fiscalDateEnding': '2013-12-31', 'reportedDate': '2014-01-30', 'reportedEPS': '0.51', 'estimatedEPS': '0.66', 'surprise': '-0.15', 'surprisePercentage': '-22.7273'}, {'fiscalDateEnding': '2013-09-30', 'reportedDate': '2013-10-24', 'reportedEPS': '-0.09', 'estimatedEPS': '-0.09', 'surprise': '0', 'surprisePercentage': '0'}, {'fiscalDateEnding': '2013-06-30', 'reportedDate': '2013-07-25', 'reportedEPS': '-0.02', 'estimatedEPS': '0.05', 'surprise': '-0.07', 'surprisePercentage': '-140'}, {'fiscalDateEnding': '2013-03-31', 'reportedDate': '2013-04-25', 'reportedEPS': '0.18', 'estimatedEPS': '0.08', 'surprise': '0.1', 'surprisePercentage': '125'}, {'fiscalDateEnding': '2012-12-31', 'reportedDate': '2013-01-29', 'reportedEPS': '0.21', 'estimatedEPS': '0.28', 'surprise': '-0.07', 'surprisePercentage': '-25'}, {'fiscalDateEnding': '2012-09-30', 'reportedDate': '2012-10-25', 'reportedEPS': '-0.23', 'estimatedEPS': '-0.08', 'surprise': '-0.15', 'surprisePercentage': '-187.5'}, {'fiscalDateEnding': '2012-06-30', 'reportedDate': '2012-07-26', 'reportedEPS': '0.16', 'estimatedEPS': '0.02', 'surprise': '0.14', 'surprisePercentage': '700'}, {'fiscalDateEnding': '2012-03-31', 'reportedDate': '2012-04-26', 'reportedEPS': '0.28', 'estimatedEPS': '0.07', 'surprise': '0.21', 'surprisePercentage': '300'}, {'fiscalDateEnding': '2011-12-31', 'reportedDate': '2012-01-31', 'reportedEPS': '0.38', 'estimatedEPS': '0.17', 'surprise': '0.21', 'surprisePercentage': '123.5294'}, {'fiscalDateEnding': '2011-09-30', 'reportedDate': '2011-10-25', 'reportedEPS': '0.14', 'estimatedEPS': '0.24', 'surprise': '-0.1', 'surprisePercentage': '-41.6667'}, {'fiscalDateEnding': '2011-06-30', 'reportedDate': '2011-07-26', 'reportedEPS': '0.41', 'estimatedEPS': '0.35', 'surprise': '0.06', 'surprisePercentage': '17.1429'}, {'fiscalDateEnding': '2011-03-31', 'reportedDate': '2011-04-26', 'reportedEPS': '0.44', 'estimatedEPS': '0.61', 'surprise': '-0.17', 'surprisePercentage': '-27.8689'}, {'fiscalDateEnding': '2010-12-31', 'reportedDate': '2011-01-27', 'reportedEPS': '0.91', 'estimatedEPS': '0.88', 'surprise': '0.03', 'surprisePercentage': '3.4091'}, {'fiscalDateEnding': '2010-09-30', 'reportedDate': '2010-10-21', 'reportedEPS': '0.51', 'estimatedEPS': '0.48', 'surprise': '0.03', 'surprisePercentage': '6.25'}, {'fiscalDateEnding': '2010-06-30', 'reportedDate': '2010-07-22', 'reportedEPS': '0.45', 'estimatedEPS': '0.54', 'surprise': '-0.09', 'surprisePercentage': '-16.6667'}, {'fiscalDateEnding': '2010-03-31', 'reportedDate': '2010-04-22', 'reportedEPS': '0.66', 'estimatedEPS': '0.61', 'surprise': '0.05', 'surprisePercentage': '8.1967'}, {'fiscalDateEnding': '2009-12-31', 'reportedDate': '2010-01-28', 'reportedEPS': '0.85', 'estimatedEPS': '0.72', 'surprise': '0.13', 'surprisePercentage': '18.0556'}, {'fiscalDateEnding': '2009-09-30', 'reportedDate': '2009-10-22', 'reportedEPS': '0.45', 'estimatedEPS': '0.33', 'surprise': '0.12', 'surprisePercentage': '36.3636'}, {'fiscalDateEnding': '2009-06-30', 'reportedDate': '2009-07-23', 'reportedEPS': '0.32', 'estimatedEPS': '0.31', 'surprise': '0.01', 'surprisePercentage': '3.2258'}, {'fiscalDateEnding': '2009-03-31', 'reportedDate': '2009-04-23', 'reportedEPS': '0.41', 'estimatedEPS': '0.31', 'surprise': '0.1', 'surprisePercentage': '32.2581'}, {'fiscalDateEnding': '2008-12-31', 'reportedDate': '2009-01-29', 'reportedEPS': '0.52', 'estimatedEPS': '0.39', 'surprise': '0.13', 'surprisePercentage': '33.3333'}, {'fiscalDateEnding': '2008-09-30', 'reportedDate': '2008-10-22', 'reportedEPS': '0.27', 'estimatedEPS': '0.25', 'surprise': '0.02', 'surprisePercentage': '8'}, {'fiscalDateEnding': '2008-06-30', 'reportedDate': '2008-07-23', 'reportedEPS': '0.37', 'estimatedEPS': '0.26', 'surprise': '0.11', 'surprisePercentage': '42.3077'}, {'fiscalDateEnding': '2008-03-31', 'reportedDate': '2008-04-23', 'reportedEPS': '0.34', 'estimatedEPS': '0.32', 'surprise': '0.02', 'surprisePercentage': '6.25'}, {'fiscalDateEnding': '2007-12-31', 'reportedDate': '2008-01-30', 'reportedEPS': '0.48', 'estimatedEPS': '0.48', 'surprise': '0', 'surprisePercentage': '0'}, {'fiscalDateEnding': '2007-09-30', 'reportedDate': '2007-10-23', 'reportedEPS': '0.19', 'estimatedEPS': '0.18', 'surprise': '0.01', 'surprisePercentage': '5.5556'}, {'fiscalDateEnding': '2007-06-30', 'reportedDate': '2007-07-24', 'reportedEPS': '0.19', 'estimatedEPS': '0.16', 'surprise': '0.03', 'surprisePercentage': '18.75'}, {'fiscalDateEnding': '2007-03-31', 'reportedDate': '2007-04-24', 'reportedEPS': '0.26', 'estimatedEPS': '0.15', 'surprise': '0.11', 'surprisePercentage': '73.3333'}, {'fiscalDateEnding': '2006-12-31', 'reportedDate': '2007-02-01', 'reportedEPS': '0.23', 'estimatedEPS': '0.21', 'surprise': '0.02', 'surprisePercentage': '9.5238'}, {'fiscalDateEnding': '2006-09-30', 'reportedDate': '2006-10-24', 'reportedEPS': '0.05', 'estimatedEPS': '0.03', 'surprise': '0.02', 'surprisePercentage': '66.6667'}, {'fiscalDateEnding': '2006-06-30', 'reportedDate': '2006-07-25', 'reportedEPS': '0.05', 'estimatedEPS': '0.06', 'surprise': '-0.01', 'surprisePercentage': '-16.6667'}, {'fiscalDateEnding': '2006-03-31', 'reportedDate': '2006-04-25', 'reportedEPS': '0.12', 'estimatedEPS': '0.12', 'surprise': '0', 'surprisePercentage': '0'}, {'fiscalDateEnding': '2005-12-31', 'reportedDate': '2006-02-02', 'reportedEPS': '0.47', 'estimatedEPS': '0.21', 'surprise': '0.26', 'surprisePercentage': '123.8095'}, {'fiscalDateEnding': '2005-09-30', 'reportedDate': '2005-10-25', 'reportedEPS': '0.07', 'estimatedEPS': '0.1', 'surprise': '-0.03', 'surprisePercentage': '-30'}, {'fiscalDateEnding': '2005-06-30', 'reportedDate': '2005-07-26', 'reportedEPS': '0.12', 'estimatedEPS': '0.11', 'surprise': '0.01', 'surprisePercentage': '9.0909'}, {'fiscalDateEnding': '2005-03-31', 'reportedDate': '2005-04-26', 'reportedEPS': '0.18', 'estimatedEPS': '0.23', 'surprise': '-0.05', 'surprisePercentage': '-21.7391'}, {'fiscalDateEnding': '2004-12-31', 'reportedDate': '2005-02-02', 'reportedEPS': '0.35', 'estimatedEPS': '0.4', 'surprise': '-0.05', 'surprisePercentage': '-12.5'}, {'fiscalDateEnding': '2004-09-30', 'reportedDate': '2004-10-21', 'reportedEPS': '0.17', 'estimatedEPS': '0.18', 'surprise': '-0.01', 'surprisePercentage': '-5.5556'}, {'fiscalDateEnding': '2004-06-30', 'reportedDate': '2004-07-22', 'reportedEPS': '0.18', 'estimatedEPS': '0.19', 'surprise': '-0.01', 'surprisePercentage': '-5.2632'}, {'fiscalDateEnding': '2004-03-31', 'reportedDate': '2004-04-22', 'reportedEPS': '0.23', 'estimatedEPS': '0.2', 'surprise': '0.03', 'surprisePercentage': '15'}, {'fiscalDateEnding': '2003-12-31', 'reportedDate': '2004-01-27', 'reportedEPS': '0.29', 'estimatedEPS': '0.29', 'surprise': '0', 'surprisePercentage': '0'}, {'fiscalDateEnding': '2003-09-30', 'reportedDate': '2003-10-21', 'reportedEPS': '0.11', 'estimatedEPS': '0.1', 'surprise': '0.01', 'surprisePercentage': '10'}, {'fiscalDateEnding': '2003-06-30', 'reportedDate': '2003-07-22', 'reportedEPS': '0.1', 'estimatedEPS': '0.06', 'surprise': '0.04', 'surprisePercentage': '66.6667'}, {'fiscalDateEnding': '2003-03-31', 'reportedDate': '2003-04-24', 'reportedEPS': '0.1', 'estimatedEPS': '0.04', 'surprise': '0.06', 'surprisePercentage': '150'}, {'fiscalDateEnding': '2002-12-31', 'reportedDate': '2003-01-23', 'reportedEPS': '0.19', 'estimatedEPS': '0.14', 'surprise': '0.05', 'surprisePercentage': '35.7143'}, {'fiscalDateEnding': '2002-09-30', 'reportedDate': '2002-10-24', 'reportedEPS': '-0.0924', 'estimatedEPS': '-0.04', 'surprise': '-0.0524', 'surprisePercentage': '-131'}, {'fiscalDateEnding': '2002-06-30', 'reportedDate': '2002-07-23', 'reportedEPS': '-0.01', 'estimatedEPS': '-0.06', 'surprise': '0.05', 'surprisePercentage': '83.3333'}, {'fiscalDateEnding': '2002-03-31', 'reportedDate': '2002-04-23', 'reportedEPS': '-0.01', 'estimatedEPS': '-0.09', 'surprise': '0.08', 'surprisePercentage': '88.8889'}, {'fiscalDateEnding': '2001-12-31', 'reportedDate': '2002-01-22', 'reportedEPS': '0.09', 'estimatedEPS': '-0.07', 'surprise': '0.16', 'surprisePercentage': '228.5714'}, {'fiscalDateEnding': '2001-09-30', 'reportedDate': '2001-10-23', 'reportedEPS': '-0.16', 'estimatedEPS': '-0.16', 'surprise': '0', 'surprisePercentage': '0'}, {'fiscalDateEnding': '2001-06-30', 'reportedDate': '2001-07-23', 'reportedEPS': '-0.16', 'estimatedEPS': '-0.22', 'surprise': '0.06', 'surprisePercentage': '27.2727'}, {'fiscalDateEnding': '2001-03-31', 'reportedDate': '2001-04-24', 'reportedEPS': '-0.21', 'estimatedEPS': '-0.25', 'surprise': '0.04', 'surprisePercentage': '16'}, {'fiscalDateEnding': '2000-12-31', 'reportedDate': '2001-01-30', 'reportedEPS': '-0.25', 'estimatedEPS': '-0.26', 'surprise': '0.01', 'surprisePercentage': '3.8462'}, {'fiscalDateEnding': '2000-09-30', 'reportedDate': '2000-10-24', 'reportedEPS': '-0.25', 'estimatedEPS': '-0.29', 'surprise': '0.04', 'surprisePercentage': '13.7931'}, {'fiscalDateEnding': '2000-06-30', 'reportedDate': '2000-07-26', 'reportedEPS': '-0.33', 'estimatedEPS': '-0.35', 'surprise': '0.02', 'surprisePercentage': '5.7143'}, {'fiscalDateEnding': '2000-03-31', 'reportedDate': '2000-04-26', 'reportedEPS': '-0.35', 'estimatedEPS': '-0.36', 'surprise': '0.01', 'surprisePercentage': '2.7778'}, {'fiscalDateEnding': '1999-12-31', 'reportedDate': '2000-02-02', 'reportedEPS': '-0.55', 'estimatedEPS': '-0.49', 'surprise': '-0.06', 'surprisePercentage': '-12.2449'}, {'fiscalDateEnding': '1999-09-30', 'reportedDate': '1999-10-27', 'reportedEPS': '-0.26', 'estimatedEPS': '-0.28', 'surprise': '0.02', 'surprisePercentage': '7.1429'}, {'fiscalDateEnding': '1999-06-30', 'reportedDate': '1999-07-21', 'reportedEPS': '-0.25', 'estimatedEPS': '-0.26', 'surprise': '0.01', 'surprisePercentage': '3.8462'}, {'fiscalDateEnding': '1999-03-31', 'reportedDate': '1999-04-28', 'reportedEPS': '-0.11', 'estimatedEPS': '-0.14', 'surprise': '0.03', 'surprisePercentage': '21.4286'}, {'fiscalDateEnding': '1998-12-31', 'reportedDate': '1999-01-26', 'reportedEPS': '-0.07', 'estimatedEPS': '-0.09', 'surprise': '0.02', 'surprisePercentage': '22.2222'}, {'fiscalDateEnding': '1998-09-30', 'reportedDate': '1998-10-28', 'reportedEPS': '-0.08', 'estimatedEPS': '-0.1', 'surprise': '0.02', 'surprisePercentage': '20'}, {'fiscalDateEnding': '1998-06-30', 'reportedDate': '1998-07-22', 'reportedEPS': '-0.07', 'estimatedEPS': '-0.07', 'surprise': '0', 'surprisePercentage': '0'}, {'fiscalDateEnding': '1998-03-31', 'reportedDate': '1998-04-27', 'reportedEPS': '-0.03', 'estimatedEPS': '-0.04', 'surprise': '0.01', 'surprisePercentage': '25'}, {'fiscalDateEnding': '1997-12-31', 'reportedDate': '1998-01-22', 'reportedEPS': '-0.03', 'estimatedEPS': '-0.04', 'surprise': '0.01', 'surprisePercentage': '25'}, {'fiscalDateEnding': '1997-09-30', 'reportedDate': '1997-10-27', 'reportedEPS': '-0.03', 'estimatedEPS': '-0.03', 'surprise': '0', 'surprisePercentage': '0'}, {'fiscalDateEnding': '1997-06-30', 'reportedDate': '1997-07-10', 'reportedEPS': '-0.02', 'estimatedEPS': '-0.03', 'surprise': '0.01', 'surprisePercentage': '33.3333'}]}

In [27]:
import pprint
# pprint.pprint(data)

resultado = pd.DataFrame(data['annualEarnings'])
resultado

   fiscalDateEnding reportedEPS
0        2022-09-30       -0.58
1        2021-12-31        3.25
2        2020-12-31        6.86
3        2019-12-31       23.01
4        2018-12-31       20.13
5        2017-12-31        4.56
6        2016-12-31        4.91
7        2015-12-31        1.24
8        2014-12-31       -0.54
9        2013-12-31        0.58
10       2012-12-31        0.42
11       2011-12-31        1.37
12       2010-12-31        2.53
13       2009-12-31        2.03
14       2008-12-31         1.5
15       2007-12-31        1.12
16       2006-12-31        0.45
17       2005-12-31        0.84
18       2004-12-31        0.93
19       2003-12-31         0.6
20       2002-12-31      0.0776
21       2001-12-31       -0.44
22       2000-12-31       -1.18
23       1999-12-31       -1.17
24       1998-12-31       -0.25
25       1997-12-31       -0.08